# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [4]:
import pandas as pd
import numpy as np

## Load the data

In [6]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [7]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         0         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create the targets

In [9]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [10]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [11]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [12]:
data_preprocessed['Excessive Absenteeism'] = targets

In [13]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         0         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [15]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [16]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week',
                                            'Daily Work Load Average','Distance to Work'],axis=1)

In [17]:
data_with_targets is data_preprocessed

False

In [18]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         0         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## Select the inputs for the regression

In [20]:
data_with_targets.shape

(700, 12)

In [21]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           0         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         0         0         0         0            5   
696         0         0         0         0            5   
697         0         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [22]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           0         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         0         0         0         0            5   
696         0         0         0         0            5   
697         0         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [23]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [25]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [26]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [27]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [28]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [29]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [30]:
# absenteeism_scaler = CustomScaler(columns_to_scale)

In [31]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [32]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [33]:
scaled_inputs

array([[-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [-0.17149859, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.17149859, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [34]:
scaled_inputs.shape

(700, 11)

## Split the data into train & test and shuffle

### Import the relevant module

In [37]:
from sklearn.model_selection import train_test_split

### Split

In [39]:
train_test_split(scaled_inputs, targets)

[array([[-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035, -0.58968976],
        [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.17149859, -0.09298136,  3.17979734, ...,  2.23224237,
         -0.01928035,  0.26848661],
        ...,
        [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.17149859, -0.09298136,  3.17979734, ..., -0.44798003,
          2.67996851, -0.58968976]]),
 array([[-0.17149859, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.17149859, -0.09298136, -0.31448545, ...,  2.23224237,
         -0.91902997, -0.58968976],
        [-0.17149859, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.17149859, -0.09298136, -0.31448545, ..., -

In [40]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8, 
                                                                            test_size = 0.2, random_state = 20)

In [41]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [42]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic regression with sklearn

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [46]:
reg = LogisticRegression()

In [47]:
reg.fit(x_train,y_train)

LogisticRegression()

In [48]:
reg.score(x_train,y_train)

0.7107142857142857

### Manually check the accuracy

In [50]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,

In [51]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [52]:
model_outputs == y_train

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True,  True, False,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [53]:
np.sum((model_outputs==y_train))

398

In [54]:
model_outputs.shape[0]

560

In [55]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7107142857142857

### Finding the intercept and coefficients

In [57]:
reg.intercept_

array([-0.09773653])

In [58]:
reg.coef_

array([[ 0.78823098, -0.0152986 ,  0.45528671, -0.54233233,  0.09808796,
         0.52299543, -0.21350095,  0.26078617, -0.12655799,  0.29056571,
        -0.28909562]])

In [59]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [60]:
feature_name = unscaled_inputs.columns.values

In [61]:
summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     0.788231
1                 Reason_2    -0.015299
2                 Reason_3     0.455287
3                 Reason_4    -0.542332
4              Month Value     0.098088
5   Transportation Expense     0.522995
6                      Age    -0.213501
7          Body Mass Index     0.260786
8                Education    -0.126558
9                 Children     0.290566
10                    Pets    -0.289096

In [62]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.097737
1                 Reason_1     0.788231
2                 Reason_2    -0.015299
3                 Reason_3     0.455287
4                 Reason_4    -0.542332
5              Month Value     0.098088
6   Transportation Expense     0.522995
7                      Age    -0.213501
8          Body Mass Index     0.260786
9                Education    -0.126558
10                Children     0.290566
11                    Pets    -0.289096

## Interpreting the coefficients

In [64]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [65]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.097737    0.906888
1                 Reason_1     0.788231    2.199502
2                 Reason_2    -0.015299    0.984818
3                 Reason_3     0.455287    1.576625
4                 Reason_4    -0.542332    0.581391
5              Month Value     0.098088    1.103060
6   Transportation Expense     0.522995    1.687074
7                      Age    -0.213501    0.807751
8          Body Mass Index     0.260786    1.297950
9                Education    -0.126558    0.881123
10                Children     0.290566    1.337184
11                    Pets    -0.289096    0.748941

In [66]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
1                 Reason_1     0.788231    2.199502
6   Transportation Expense     0.522995    1.687074
3                 Reason_3     0.455287    1.576625
10                Children     0.290566    1.337184
8          Body Mass Index     0.260786    1.297950
5              Month Value     0.098088    1.103060
2                 Reason_2    -0.015299    0.984818
0                Intercept    -0.097737    0.906888
9                Education    -0.126558    0.881123
7                      Age    -0.213501    0.807751
11                    Pets    -0.289096    0.748941
4                 Reason_4    -0.542332    0.581391

## Testing the model

In [68]:
reg.score(x_test,y_test)

0.6857142857142857

In [69]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.70343447, 0.29656553],
       [0.61240562, 0.38759438],
       [0.47462102, 0.52537898],
       [0.74795727, 0.25204273],
       [0.00218786, 0.99781214],
       [0.49550331, 0.50449669],
       [0.49123745, 0.50876255],
       [0.09830964, 0.90169036],
       [0.75210933, 0.24789067],
       [0.72625951, 0.27374049],
       [0.5311253 , 0.4688747 ],
       [0.25151455, 0.74848545],
       [0.05224213, 0.94775787],
       [0.74284651, 0.25715349],
       [0.24889585, 0.75110415],
       [0.55978449, 0.44021551],
       [0.56578831, 0.43421169],
       [0.558896  , 0.441104  ],
       [0.63237075, 0.36762925],
       [0.04269649, 0.95730351],
       [0.69632174, 0.30367826],
       [0.74795727, 0.25204273],
       [0.59626561, 0.40373439],
       [0.59626561, 0.40373439],
       [0.15832337, 0.84167663],
       [0.72509328, 0.27490672],
       [0.53157488, 0.46842512],
       [0.84903178, 0.15096822],
       [0.13788978, 0.86211022],
       [0.74795727, 0.25204273],
       [0.

In [70]:
predicted_proba.shape

(140, 2)

In [71]:
predicted_proba[:,1]

array([0.29656553, 0.38759438, 0.52537898, 0.25204273, 0.99781214,
       0.50449669, 0.50876255, 0.90169036, 0.24789067, 0.27374049,
       0.4688747 , 0.74848545, 0.94775787, 0.25715349, 0.75110415,
       0.44021551, 0.43421169, 0.441104  , 0.36762925, 0.95730351,
       0.30367826, 0.25204273, 0.40373439, 0.40373439, 0.84167663,
       0.27490672, 0.46842512, 0.15096822, 0.86211022, 0.25204273,
       0.36136241, 0.51295978, 0.51849091, 0.48284368, 0.25204273,
       0.53328018, 0.25314874, 0.83919881, 0.3821374 , 0.57091619,
       0.24680004, 0.30041267, 0.26388389, 0.80080362, 0.99480878,
       0.7264988 , 0.52931348, 0.29656553, 0.24046465, 0.24163117,
       0.36882111, 0.74297376, 0.50449669, 0.27247465, 0.65662705,
       0.40096995, 0.91712741, 0.26573879, 0.75975331, 0.76482779,
       0.50242529, 0.49749556, 0.30569671, 0.85945633, 0.22957614,
       0.28501562, 0.44763966, 0.25314874, 0.82440782, 0.27912703,
       0.25314874, 0.70935132, 0.77475232, 0.41569764, 0.57477

## Save the model

In [73]:
import pickle

In [74]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [75]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler, file)